name=SoundPlayerEC
version=1.0.0
author=ec2021
maintainer=ec2021
sentence=Eine einfache Wrapper-Library für den DFRobotDFPlayerMini.
paragraph=Unterstützt ESP32 (HardwareSerial) und AVR (SoftwareSerial).
category=Device Control
url=https://github.com
architectures=*
depends=DFRobotDFPlayerMini
