name=SoundPlayerEC
version=1.0.0
author=ec2021
maintainer=ec2021
sentence=A simple wrapper library for the DFRobotDFPlayerMini.
paragraph=Supports ESP32 (HardwareSerial) and AVR (SoftwareSerial) architectures.
category=Device Control
url=https://github.com
architectures=*
depends=DFRobotDFPlayerMini
