name=SoundPlayer
version=1.0.0
author=Dein Name
maintainer=Dein Name
sentence=Eine einfache Wrapper-Library für den DFRobotDFPlayerMini.
paragraph=Unterstützt ESP32 (HardwareSerial) und AVR (SoftwareSerial).
category=Device Control
url=https://github.com
architectures=*
depends=DFRobotDFPlayerMini
